Deprecated smp_mb__after_clear_bit has been removed from the mainline
The current linaro-android-3.18 topic gives the following build error:
-----8<-----
../arch/arm/kernel/smp.c: In function ‘smp_send_all_cpu_backtrace’:
../arch/arm/kernel/smp.c:588:2: error: implicit declaration of function ‘smp_mb__after_clear_bit’ [-Werror=implicit-function-declaration]
  smp_mb__after_clear_bit();
  ^
-----8<-----

The reason is:
commit 2e39465abc4b7856a0ea6fcf4f6b4668bb5db877
    "locking: Remove deprecated smp_mb__() barriers"
commit 030d0178bdbd237c1f0577f03bbc1d7140a75044,
    "arch,arm: Convert smp_mb__*()"

Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>