trace: fix aosp's non-hierarchical function_graph build
AOSP commit 6f6f99a38132 "trace: add non-hierarchical
function_graph option", run into following build error:
--------------------
  CC      kernel/trace/trace_output.o
kernel/trace/trace_output.c: In function ‘trace_graph_ent_trace’:
kernel/trace/trace_output.c:906:2: error: invalid use of void expression
kernel/trace/trace_output.c:912:2: error: invalid use of void expression
kernel/trace/trace_output.c: In function ‘trace_graph_ent_raw’:
kernel/trace/trace_output.c:927:10: error: invalid use of void expression
kernel/trace/trace_output.c: In function ‘trace_graph_ent_hex’:
kernel/trace/trace_output.c:941:2: error: implicit declaration of function ‘SEQ_PUT_HEX_FIELD_RET’ [-Werror=implicit-function-declaration]
kernel/trace/trace_output.c: In function ‘trace_graph_ent_bin’:
kernel/trace/trace_output.c:955:2: error: implicit declaration of function ‘SEQ_PUT_FIELD_RET’ [-Werror=implicit-function-declaration]
kernel/trace/trace_output.c: In function ‘trace_graph_ret_trace’:
kernel/trace/trace_output.c:983:2: error: invalid use of void expression
kernel/trace/trace_output.c:989:2: error: invalid use of void expression
kernel/trace/trace_output.c: In function ‘trace_graph_ret_raw’:
kernel/trace/trace_output.c:1007:10: error: invalid use of void expression
cc1: some warnings being treated as errors
make[2]: *** [kernel/trace/trace_output.o] Error 1
make[1]: *** [kernel/trace] Error 2
make[1]: *** Waiting for unfinished jobs....
--------------------

Fixes:
1) Do not use return value of trace_seq_printf() in syscall
tracing, use trace_seq_has_overflowed() instead
(mainline commit 183742f08c55).

2) Use SEQ_PUT_{FIELD,HEX_FIELD} macros instead of obsolete
SEQ_PUT_{FIELD_RET,HEX_FIELD_RET} macros (mainline commit
19a7fe206232, "tracing: Add trace_seq_has_overflowed() and
trace_handle_return()").

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>