cpufreq: interactive: build fixes
Folded following build fixes in this commit.

* cpufreq: interactive: build fixes for 4.4

  Bring back cpufreq_{get,put}_global_kobject() definitions
  removed by upstream commit 8eec1020f0c0 "cpufreq: create
  cpu/cpufreq at boot time" to fix build failures.

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* cpufreq: interactive: replace strict_strtoul() with kstrtoul()

  strict_strtoul() is obsolete. Use kstrtoul() instead.
  Otherwise we run into following build error:

    CC      drivers/cpufreq/cpufreq_interactive.o
  drivers/cpufreq/cpufreq_interactive.c: In function ‘store_hispeed_freq’:
  drivers/cpufreq/cpufreq_interactive.c:784:2: error: implicit declaration of function ‘strict_strtoul’ [-Werror=implicit-function-declaration]
  cc1: some warnings being treated as errors
  make[2]: *** [drivers/cpufreq/cpufreq_interactive.o] Error 1

  Change-Id: Ib91b9df3af5fe2a244861c2f598bd20ec8115e6c
  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* cpufreq: interactive: fix compiling warnings

  The gcc warns like:

    cpufreq_interactive.c:745:6: warning: operation on 'ret' may be undefined [-Wsequence-point]

  It was introduced by commit cf0fad49d17cb8273ce555dd5b7afab67d7923bf.

  Since sprintf(...) just return 1 (one character) in this case, ret should not changed.
  Just discarding the result of sprintf(...) leads to the result that
  the committer of cf0fad49d17cb8273ce555dd5b7afab67d7923bf wants.

  Change-Id: Ifed1cef6d6a31c3ed23dad03a567b3b9eddf3a57
  Signed-off-by: Chih-Wei Huang <cwhuang@android-x86.org>

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>