Fix xt_qtaguid build error
Add missing header <linux/miscdevice.h> and export
xt_socket_lookup_slow_v* functions to be used in
xt_qtaguid, otherwise we run into following error:
------------------
  CC      net/netfilter/xt_qtaguid.o
net/netfilter/xt_qtaguid.c: In function ‘qtaguid_find_sk’:
net/netfilter/xt_qtaguid.c:1591:3: error: implicit declaration of function ‘xt_socket_lookup_slow_v6’ [-Werror=implicit-function-declaration]
net/netfilter/xt_qtaguid.c:1591:6: warning: assignment makes pointer from integer without a cast [enabled by default]
net/netfilter/xt_qtaguid.c:1594:3: error: implicit declaration of function ‘xt_socket_lookup_slow_v4’ [-Werror=implicit-function-declaration]
net/netfilter/xt_qtaguid.c:1594:6: warning: assignment makes pointer from integer without a cast [enabled by default]
net/netfilter/xt_qtaguid.c: At top level:
net/netfilter/xt_qtaguid.c:2902:15: error: variable ‘qtu_device’ has initializer but incomplete type
net/netfilter/xt_qtaguid.c:2903:2: error: unknown field ‘minor’ specified in initializer
net/netfilter/xt_qtaguid.c:2903:11: error: ‘MISC_DYNAMIC_MINOR’ undeclared here (not in a function)
net/netfilter/xt_qtaguid.c:2903:2: warning: excess elements in struct initializer [enabled by default]
net/netfilter/xt_qtaguid.c:2903:2: warning: (near initialization for ‘qtu_device’) [enabled by default]
net/netfilter/xt_qtaguid.c:2904:2: error: unknown field ‘name’ specified in initializer
net/netfilter/xt_qtaguid.c:2904:2: warning: excess elements in struct initializer [enabled by default]
net/netfilter/xt_qtaguid.c:2904:2: warning: (near initialization for ‘qtu_device’) [enabled by default]
net/netfilter/xt_qtaguid.c:2905:2: error: unknown field ‘fops’ specified in initializer
net/netfilter/xt_qtaguid.c:2905:2: warning: excess elements in struct initializer [enabled by default]
net/netfilter/xt_qtaguid.c:2905:2: warning: (near initialization for ‘qtu_device’) [enabled by default]
net/netfilter/xt_qtaguid.c: In function ‘qtaguid_mt_init’:
net/netfilter/xt_qtaguid.c:3014:6: error: implicit declaration of function ‘misc_register’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[2]: *** [net/netfilter/xt_qtaguid.o] Error 1
make[1]: *** [net/netfilter] Error 2
make: *** [net] Error 2
make: *** Waiting for unfinished jobs....
------------------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>