staging: android: lowmemorykiller: Fix __module_param_call build error
Fix build error related to "__module_param_call":
-----8<-----
drivers/staging/android/lowmemorykiller.c:282:28:
error: macro "__module_param_call" requires 7 arguments, but only 6 given
----->8-----

Upstream commit 91f9d330cc14932084c37751997213cb0e7ea882
"module: make it possible to have unsafe, tainting module params",
adds an additional argument in __module_param_call() which needed
to be taken care of in drivers/staging/android/lowmemorykiller.c

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>