UPSTREAM: scsi: ufs: Fix kernel-doc errors and warnings
Avoid that the kernel-doc tool complains about mismatches between
kernel-doc headers and function definitions. Avoid that errors like the
following are reported when building the UFS driver with W=1:

drivers/scsi/ufs/tc-dwc-g210-pci.c:60: error: Cannot parse struct or union!
drivers/scsi/ufs/tc-dwc-g210-pltfrm.c:26: warning: cannot understand function prototype: 'struct ufs_hba_variant_ops tc_dwc_g210_20bit_pltfm_hba_vops = '

Signed-off-by: Bart Van Assche <bart.vanassche@wdc.com>
Cc: Vivek Gautam <vivek.gautam@codeaurora.org>
Cc: Stanislav Nijnikov <stanislav.nijnikov@wdc.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

BUG=b:74254727
TEST=Build kernel for Cheza

Change-Id: I0380c03e057b8064b0eb13d9cacc9dbe6561cd1f
Signed-off-by: Evan Green <evgreen@chromium.org>
(cherry picked from commit 8aa29f192ca675746ab4f39e46a5fd712a76faa6)
Reviewed-on: https://chromium-review.googlesource.com/1056313
Commit-Ready: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>