usb: gadget: build fixes
Folded following build fixes in this commit.

* usb: gadget: u_ether: use %z format specifier for size_t

  Use '%zd' format specifier for size_t type instead
  of '%d' to fix build warnings like:

  drivers/usb/gadget/function/u_ether.c: In function ‘rx_submit’:
  drivers/usb/gadget/function/u_ether.c:244:2: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t’ [-Wformat=]
    DBG(dev, "%s: size: %d\n", __func__, size);
    ^

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* usb: gadget: rndis: fix broken build for 4.4

  Use rndis_params instead of configNr to align with
  changes from mainline commit 83210e59ee15
  "usb: gadget: rndis: use rndis_params instead of configNr".

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* usb: gadget: rndis: fix broken data aggregation build

  Declare "cdev" to fix broken AOSP commit
  "RNDIS: Add Data aggregation (multi packet) support",
  otherwise we run into following build failure:

    CC      drivers/usb/gadget/function/f_rndis.o
  drivers/usb/gadget/function/f_rndis.c: In function ‘rndis_command_complete’:
  drivers/usb/gadget/function/f_rndis.c:479:3: error: ‘cdev’ undeclared (first use in this function)
  drivers/usb/gadget/function/f_rndis.c:479:3: note: each undeclared identifier is reported only once for each function it appears in
  make[4]: *** [drivers/usb/gadget/function/f_rndis.o] Error 1

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* usb: gadget: rndis: use %z format specifier for size_t

  Use '%z' format specifier for sizeof operator instead
  of '%u' to fix build warnings like:

      warning: format '%u' expects type 'unsigned int', but argument 3 has type 'long unsigned int'

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* usb: gadget: cleanup: fix unused variable and function warnings

  Remove unused variables and functions to fix following
  build warnings like ...

    drivers/usb/gadget/configfs.c: In function ‘gadgets_make’:
    drivers/usb/gadget/configfs.c:1710:6: warning: unused variable ‘err’ [-Wunused-variable]

    drivers/usb/gadget/function/f_mtp.c:1219:12: warning: ‘mtp_bind_config’ defined but not used [-Wunused-function]
     static int mtp_bind_config(struct usb_configuration *c, bool ptp_config)

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* usb: gadget: build audio_source function only if SND is enabled

  Also select SND_PCM while building f_audio_source
  otherwise we run into following build error:

    LD      init/built-in.o
  drivers/built-in.o: In function `audio_data_complete':
  drivers/usb/gadget/function/f_audio_source.c:458: undefined reference to `snd_pcm_period_elapsed'
  drivers/built-in.o: In function `audio_pcm_hw_free':
  drivers/usb/gadget/function/f_audio_source.c:770: undefined reference to `snd_pcm_lib_free_vmalloc_buffer'
  drivers/built-in.o: In function `snd_pcm_lib_alloc_vmalloc_buffer':
  include/sound/pcm.h:1179: undefined reference to `_snd_pcm_lib_alloc_vmalloc_buffer'
  drivers/built-in.o: In function `audio_pcm_open':
  drivers/usb/gadget/function/f_audio_source.c:734: undefined reference to `snd_pcm_limit_hw_rates'
  drivers/built-in.o: In function `snd_card_setup':
  drivers/usb/gadget/function/f_audio_source.c:888: undefined reference to `snd_pcm_new'
  drivers/usb/gadget/function/f_audio_source.c:898: undefined reference to `snd_pcm_set_ops'
  drivers/usb/gadget/function/f_audio_source.c:899: undefined reference to `snd_pcm_lib_preallocate_pages_for_all'
  drivers/built-in.o:(.data+0x1fd28): undefined reference to `snd_pcm_lib_ioctl'
  make: *** [vmlinux] Error 1

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* usb: u_ether: Fix compile errors

  commit f1a1823ff24fa4e3412b5078f20021cf40834946
  usb: gadget: u_ether: convert into module

  changes qlen function definition. and this has to be fixed
  accordingly in current u_ether driver.

  This patch fixes following compile error in u_ether caused by commit.

  drivers/usb/gadget/u_ether.c: In function 'rx_fill':
  drivers/usb/gadget/u_ether.c:416:3: error: too few arguments to function 'qlen'
     if (++req_cnt > qlen(dev->gadget))
     ^

  drivers/usb/gadget/u_ether.c: In function 'eth_start_xmit':
  drivers/usb/gadget/u_ether.c:738:24: error: 'qmult' undeclared (first use in this function)
     if (dev->tx_qlen == (qmult/2)) {

  which was caused by commits
  commit 79467317949e1621240f632acfb7453783bec2e7
  USB: gadget: u_ether: Fix data stall issue in RNDIS tethering mode

  commit 68b91e8c54f5c091986c5719631893b10eab760a
  usb: u_ether: Add workqueue as bottom half handler for rx data path

  Change-Id: Ic4e5a1e08cb688e5a606c7c1895f869d8f887b9f
  Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>

* drivers: usb: gadget: 64-bit related type fixes

  Change-Id: I2f9b12e1e0cdfe64ffe20db78d319a6221821184
  Signed-off-by: Greg Hackmann <ghackmann@google.com>

* usb: gadget: Fix android gadget driver build

  Removed obsolete f_adb function

  Change-Id: Idfb4110429bc0ea63f493c68ad667f49ca471987
  Signed-off-by: Benoit Goby <benoit@android.com>

* usb: gadget: android: Fixes and hacks to make android usb gadget compile on 3.8

  Change-Id: I332a6802dbd49b4018b9318b8621d26ed94c955d
  Signed-off-by: Arve Hjønnevåg <arve@android.com>

* usb: gadget: accessory: Fix section mismatch (again)

  create_bulk_endpoints should not be __init since it is called when
  accessory is enabled.

  Change-Id: Iac6e9f29d53c93760e926efd8e7603432632acb4
  Signed-off-by: Todd Poynor <toddpoynor@google.com>

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>