net: netfilter: build fixes
Folded following build fixes in this commit.

* netfilter: xt_qtaguid/socket: build fixes for 4.4

  Update xt_socket_lookup_slow_v* usage in aosp patches, to
  align with changes from mainline commit 686c9b50809d
  "netfilter: x_tables: Use par->net instead of computing
  from the passed net devices".

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* netfilter: xt_qtaguid: xt_socket: build fixes

  Add missing header <linux/miscdevice.h> and use
  xt_socket_lookup_slow_v* instead of xt_socket_get*_sk
  in xt_qtaguid.c.

  Fix xt_socket_lookup_slow_v* functions in xt_socket.c
  and declare them in xt_socket.h

  Change-Id: I55819b2d4ffa82a2be20995c87d28fb5cc77b5ba
  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* xt_qtaguid: use sock_gen_put() instead of xt_socket_put_sk()

  Removing obsolete xt_socket_put_sk() and using sock_gen_put() instead.
  xt_socket_put_sk() was reintroduced for xt_qtaguid in one of the patches,
  but it turned out sock_gen_put() supersedes xt_socket_put_sk(). So we
  don't need xt_socket_put_sk() any more.

  This patch is based on commit 1a8bf6eeef9f (netfilter: xt_socket: use sock_gen_put())

  Change-Id: I976d5f7f7eded0f3cc91b596acfeb35e4c2057e5
  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* xt_qtaguid: fix broken uid/gid range check

  The existing test to check if current uid/gid is within
  valid range is broken due to missing parenthesis.

  Change-Id: I889ebbd0e2ea6a9426cb1509a2975e7107666407
  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* netfilter: Build fixups - kuid/kguid changes & xt_socket_get/put_sk

  Fix up build kuid/kguid build issues in netfilter code.

  Also re-add the xt_socket_get/put_sk interfaces needed by xt_qtaguid.

  Change-Id: I7027fb840e109785bddffe8ea717b8d018b26d82
  Signed-off-by: John Stultz <john.stultz@linaro.org>

* nf: IDLETIMER: Fix broken uid field in the msg

  Create uid from kuid to fix the broken uid field
  in the message notifications introduced in
  Change-Id: I18fc73eada512e370d7ab24fc9f890845037b729,
  Otherwise we run into following build error:
  ---------------
    CC      net/netfilter/xt_IDLETIMER.o
  net/netfilter/xt_IDLETIMER.c: In function ‘reset_timer’:
  net/netfilter/xt_IDLETIMER.c:360:16: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
  make[2]: *** [net/netfilter/xt_IDLETIMER.o] Error 1
  ---------------

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
  (cherry picked from commit 706060ba3e1dee9ec3c4a4a1480d663b6cd71cad)

  Change-Id: Ifd66df45a58d1a5a60c3816c373ee3008292eee8

* netfilter: fix seq_printf type mismatch warning

  The return type of atomic64_read() varies depending on arch.  The
  arm64 version is being changed from long long to long in the mainline
  for v3.16, causing a seq_printf type mismatch (%llu) in
  guid_ctrl_proc_show().

  This commit fixes the type mismatch by casting atomic64_read() to u64.

  Change-Id: Iae0a6bd4314f5686a9f4fecbe6203e94ec0870de
  Signed-off-by: Sherman Yin <shermanyin@gmail.com>

* nf: Remove compilation error caused by e8430cbed3ef15fdb1ac26cfd020e010aa5f1c35

  Signed-off-by: Ruchi Kandoi <kandoiruchi@google.com>

* xt_qtaguid: Fix boot panic

  We need the change below because of mainline commit 351638e7de (net: pass
  info struct via netdevice notifier). Otherwise we panic.

  Change-Id: I7daf7513a733933fdcbaeebea7f8191f8b6a0432
  Signed-off-by: John Stultz <john.stultz@linaro.org>

* net: kuid/kguid build fixes

  Small build fixes for xt_quota2 and ipv4 changes

  Change-Id: Ib098768040c8875887b2081c3165a6c83b37e180
  Signed-off-by: John Stultz <john.stultz@linaro.org>

* netfilter: xt_qtaguid: 64-bit warning fixes

  Change-Id: I2adc517c0c51050ed601992fa0ea4de8f1449414
  Signed-off-by: Greg Hackmann <ghackmann@google.com>

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>