arch/arm64/kernel/signal32.c: fix a merge error
Commit db2413ad14d0 ("Merge branch 'linaro-fixes/android-3.18' into
linaro-android-llct") causes the following error:

arch/arm64/kernel/signal32.c: In function ‘copy_siginfo_to_user32’:
arch/arm64/kernel/signal32.c:195:2: error: duplicate case value
  case __SI_SYS:
  ^
arch/arm64/kernel/signal32.c:188:2: error: previously used here
  case __SI_SYS:
  ^
scripts/Makefile.build:258: recipe for target 'arch/arm64/kernel/signal32.o' failed
make[2]: *** [arch/arm64/kernel/signal32.o] Error 1

Commit cc5e9097c9aad6b1 "arm64: add SIGSYS siginfo for compat task" has been
accepted upstream. But linaro-fixes/android-3.18 still carries its older
version - commit 17fa5771f529bf9d.

Reported-by: Jon Medhurst (Tixy) tixy@linaro.org
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>