net: PPPoPNS and PPPoLAC build fixes
Folded following build fixes in this commit.

* net: PPPoPNS and PPPoLAC build fixes for 4.4

  Fix couple of sk_alloc() calls to align with mainline commit
  11aa9c28b420 "net: Pass kern from net_proto_family.create to sk_alloc".

  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* Hack: net: PPPoPNS and PPPoLAC build fixes for 4.1

  Upstream commit c0371da6047a "put iov_iter into msghdr",
  added iov_iter and removed direct access to scatter/gather
  array elements in msghdr. It broke PPPoLAC and PPPoPNS.

  Lets restore the direct access to scatter/gather array in
  msghdr for the time being. Otherwise we run into following
  build failure:
  ----------
  drivers/net/ppp/pppolac.c: In function ‘pppolac_xmit_core’:
  drivers/net/ppp/pppolac.c:210:4: error: unknown field ‘msg_iov’ specified in initializer
      .msg_iov = (struct iovec *)&iov,
      ^
  drivers/net/ppp/pppolac.c:211:4: error: unknown field ‘msg_iovlen’ specified in initializer
      .msg_iovlen = 1,
      ^
  make[3]: *** [drivers/net/ppp/pppolac.o] Error 1
  ----------

  Change-Id: I2a1245a156da6d93b49f5cfd10506381b0eff005
  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* net: pppopns: pppolac: fix sendmsg function calls

  Fix couple of sendmsg() calls to align with changes
  from upstream commit 1b784140474e "net: Remove iocb
  argument from sendmsg and recvmsg".

  Change-Id: I85bc46130af8decfa37abe65aec33053ed39f1b1
  Signed-off-by: Amit Pundir <amit.pundir@linaro.org>

* net: PPPoPNS: Remove length argument from data_ready

  The argument was removed by commit 676d23690fb6 ("net: Fix use after free by
  removing length arg from sk_data_ready callbacks") and it's presence causes
  warnings like:

  drivers/net/ppp/pppopns.c:296:27: warning: assignment from incompatible pointer type
    po->proto.pns.data_ready = sk_raw->sk_data_ready;

  Change-Id: I0a7f9cf092816554a9dc1c20a64c3bbf2be2a3ca
  Signed-off-by: Jon Medhurst <tixy@linaro.org>

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>