power: suspend_time: include module.h instead of init.h
Include module.h instead of init.h since module_{init,exit}
is no longer part of init.h, they have been moved to module.h
instead. See mainline commit 0fd972a7d91d "module: relocate
module_init from init.h to module.h" for more details.

Otherwise we run into following build failure:
--------------------
  CC      kernel/power/suspend_time.o
kernel/power/suspend_time.c:110:1: warning: data definition has no type or storage class [enabled by default]
kernel/power/suspend_time.c:110:1: error: type defaults to ‘int’ in declaration of ‘module_init’ [-Werror=implicit-int]
kernel/power/suspend_time.c:110:1: warning: parameter names (without types) in function declaration [enabled by default]
kernel/power/suspend_time.c:111:1: warning: data definition has no type or storage class [enabled by default]
kernel/power/suspend_time.c:111:1: error: type defaults to ‘int’ in declaration of ‘module_exit’ [-Werror=implicit-int]
kernel/power/suspend_time.c:111:1: warning: parameter names (without types) in function declaration [enabled by default]
kernel/power/suspend_time.c:99:12: warning: ‘suspend_time_syscore_init’ defined but not used [-Wunused-function]
kernel/power/suspend_time.c:106:13: warning: ‘suspend_time_syscore_exit’ defined but not used [-Wunused-function]
cc1: some warnings being treated as errors
make[2]: *** [kernel/power/suspend_time.o] Error 1
make[1]: *** [kernel/power] Error 2
make[1]: *** Waiting for unfinished jobs....
--------------------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>