usb: gadget: audio_source function depends on SND_PCM
Select f_audio_source usb function only if SND_PCM is
enabled otherwise we run into following build error:
-------------------------------
  LD      init/built-in.o
drivers/built-in.o: In function `audio_data_complete':
drivers/usb/gadget/function/f_audio_source.c:458: undefined reference to `snd_pcm_period_elapsed'
drivers/built-in.o: In function `audio_pcm_hw_free':
drivers/usb/gadget/function/f_audio_source.c:770: undefined reference to `snd_pcm_lib_free_vmalloc_buffer'
drivers/built-in.o: In function `snd_pcm_lib_alloc_vmalloc_buffer':
include/sound/pcm.h:1180: undefined reference to `_snd_pcm_lib_alloc_vmalloc_buffer'
drivers/built-in.o: In function `audio_pcm_open':
drivers/usb/gadget/function/f_audio_source.c:734: undefined reference to `snd_pcm_limit_hw_rates'
drivers/built-in.o: In function `audio_source_alloc_inst':
drivers/usb/gadget/function/f_audio_source.c:1011: undefined reference to `create_function_device'
drivers/built-in.o: In function `snd_card_setup':
drivers/usb/gadget/function/f_audio_source.c:888: undefined reference to `snd_pcm_new'
drivers/usb/gadget/function/f_audio_source.c:898: undefined reference to `snd_pcm_set_ops'
drivers/usb/gadget/function/f_audio_source.c:899: undefined reference to `snd_pcm_lib_preallocate_pages_for_all'
drivers/built-in.o:(.data+0x20ca8): undefined reference to `snd_pcm_lib_ioctl'
make: *** [vmlinux] Error 1
-------------------------------

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>